// Condensed comment block.

using Microsoft.AspNetCore.Http;

namespace RecipeSharingAPI.Models
{
    /// <summary>
    public class Recipe
    {
        // Primary key - auto-generated by MySQL
        public int RecipeId { get; set; }

        // Recipe title - indexed in DB for fast search
        public string Title { get; set; } = string.Empty;

        // Comma-separated list of ingredients
        // Has FULLTEXT index for natural language search
        public string Ingredients { get; set; } = string.Empty;

        // Step-by-step cooking instructions
        public string Steps { get; set; } = string.Empty;

        // URL to the recipe's image (optional)
        public string? ImageUrl { get; set; }

        // Cooking time in minutes
        public int? CookingTime { get; set; }

        // Number of servings the recipe makes
        public int? Servings { get; set; }

        // Foreign key to the Users table (who created this recipe)
        public int UserId { get; set; }

        // Foreign key to the Categories table
        public int CategoryId { get; set; }

        // Joined fields - populated via SQL JOINs, not stored in Recipes table
        // These provide denormalized display data without breaking 3NF in the DB
        public string AuthorName { get; set; } = string.Empty;
        public string CategoryName { get; set; } = string.Empty;

        // Calculated field - average of all ratings for this recipe
        public double AverageRating { get; set; }

        // Timestamps for auditing
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        // Analytics data
        public int Views { get; set; }
    }

    /// <summary>
    public class RecipeDto
    {
        public string Title { get; set; } = string.Empty;
        public string Ingredients { get; set; } = string.Empty;
        public string Steps { get; set; } = string.Empty;
        public string? ImageUrl { get; set; }
        public IFormFile? ImageFile { get; set; } // Field for file upload payload
        public int? CookingTime { get; set; }
        public int? Servings { get; set; }
        public int CategoryId { get; set; }
    }
}
