// Condensed comment block.

namespace RecipeSharingAPI.Models
{
    /// <summary>
    public class User
    {
        // Unique identifier auto-generated by MySQL (AUTO_INCREMENT)
        public int UserId { get; set; }

        // User's display name shown on recipes and comments
        public string FullName { get; set; } = string.Empty;

        // Email used for login - must be unique across all users
        public string Email { get; set; } = string.Empty;

        // BCrypt hashed password - NEVER stored or transmitted as plain text
        public string PasswordHash { get; set; } = string.Empty;

        // Timestamp when the user registered
        public DateTime CreatedAt { get; set; }
        
        // Admin or User role
        public string Role { get; set; } = "User";

        // Details about last login time for analytics
        public DateTime? LastLogin { get; set; }
    }

    /// <summary>
    public class RegisterDto
    {
        public string FullName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;

        // Plain text password from client - will be hashed before storage
        public string Password { get; set; } = string.Empty;
    }

    /// <summary>
    public class LoginDto
    {
        public string Email { get; set; } = string.Empty;
        public string Password { get; set; } = string.Empty;
    }

    /// <summary>
    public class AuthResponse
    {
        public string Token { get; set; } = string.Empty;
        public int UserId { get; set; }
        public string FullName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string Role { get; set; } = "User";
    }
}
